logging:
  level:
    root: INFO
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
